name: marvel_rivals_mod_manager
description: Mod Manager for Marvel Rivals 2.0
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  path_provider: ^2.0.15
  file_picker: ^6.1.1
  process_run: ^0.13.1
  platform: ^3.1.0
  path: ^1.8.3
  http: ^1.2.0
  ffi: ^2.1.0
  win32: ^5.0.9
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  crypto: ^3.0.3
  archive: ^3.4.9
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  json_annotation: ^4.9.0
  desktop_drop: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.9.4
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/img/cover.png
    - assets/lang/ 